export type Player = { uniform: string; name: string; pos: string; bt: string; yob: number }
export type Coach  = { uniform: string; name: string; role: string }
export type TeamRoster = { players: Player[]; coaches: Coach[] }
export type StaticRosters = Record<string, TeamRoster>

export const ROSTERS: StaticRosters = {
  pirates: {
    players: [
      { uniform: '84', name: 'Mihai Bracacescu',     pos: 'C',  bt: 'L/R', yob: 2005 },
      { uniform: '7',  name: 'Dennis Burgersdijk',   pos: 'P',  bt: 'S/R', yob: 1988 },
      { uniform: '53', name: 'Quintin De Cuba',       pos: 'IF', bt: 'R/R', yob: 1987 },
      { uniform: '9',  name: 'Victor Draijer',        pos: 'OF', bt: 'L/R', yob: 1993 },
      { uniform: '31', name: 'Julian Goins',          pos: 'C',  bt: 'L/R', yob: 1994 },
      { uniform: '92', name: 'Daan Hijzelendoorn',    pos: 'P',  bt: 'S/R', yob: 2007 },
      { uniform: '39', name: 'Lars Huijer',           pos: 'P',  bt: 'R/R', yob: 1993 },
      { uniform: '1',  name: 'Jason Jakobus',         pos: 'OF', bt: 'R/R', yob: 1986 },
      { uniform: '51', name: 'Sedley Karel',          pos: 'P',  bt: 'S/R', yob: 1990 },
      { uniform: '72', name: 'Yassir Lachkar',        pos: 'P',  bt: 'S/R', yob: 2001 },
      { uniform: '13', name: 'Alex Madera',           pos: 'IF', bt: 'L/R', yob: 1997 },
      { uniform: '16', name: 'Brendly Martina',       pos: 'IF', bt: 'R/R', yob: 1996 },
      { uniform: '4',  name: 'Junior Martina',        pos: 'IF', bt: 'R/R', yob: 1997 },
      { uniform: '65', name: 'Thibaud Pastor',        pos: 'IF', bt: 'L/R', yob: 2005 },
      { uniform: '28', name: 'Jorrit Penseel',        pos: 'IF', bt: 'L/R', yob: 2000 },
      { uniform: '48', name: 'Connor Prins',          pos: 'P',  bt: 'L/R', yob: 2003 },
      { uniform: '17', name: 'Danyll Redan',          pos: 'P',  bt: 'R/R', yob: 2008 },
      { uniform: '3',  name: 'Martijn Schoonderwoerd',pos: 'P',  bt: 'R/R', yob: 1997 },
      { uniform: '6',  name: 'Delano Selassa',        pos: 'IF', bt: 'S/R', yob: 1999 },
      { uniform: '32', name: 'Jeandro Tromp',         pos: 'OF', bt: 'S/R', yob: 2000 },
      { uniform: '23', name: 'Tommy Van De Sanden',   pos: 'OF', bt: 'L/R', yob: 1999 },
      { uniform: '25', name: 'Pim Vijfvinkel',        pos: 'P',  bt: 'S/R', yob: 2001 },
    ],
    coaches: [
      { uniform: '2',  name: 'Mervin Gario',    role: 'Manager/Head coach' },
      { uniform: '21', name: 'Gaetano Cristiano',role: 'Coach' },
      { uniform: '22', name: 'Shane Gnade',      role: 'Pitching Coach' },
      { uniform: '30', name: 'Roeland Henrique', role: 'Coach' },
      { uniform: '88', name: 'Glenn Koolman',    role: 'Coach' },
      { uniform: '27', name: 'Danny Rombley',    role: 'Coach' },
    ],
  },

  hcaw: {
    players: [
      { uniform: '15', name: 'Jesse Aussems',       pos: 'IF', bt: 'L/R', yob: 1992 },
      { uniform: '6',  name: 'Daan Baltus',         pos: 'IF', bt: 'L/R', yob: 2006 },
      { uniform: '21', name: 'Maxwell Cornelissen', pos: 'P',  bt: 'L/L', yob: 2005 },
      { uniform: '14', name: 'Gio De Graauw',       pos: 'P',  bt: 'R/R', yob: 2002 },
      { uniform: '72', name: 'Nathan Diaby',        pos: 'P',  bt: 'R/R', yob: 1999 },
      { uniform: '8',  name: 'Arij Fransen',        pos: 'P',  bt: 'R/R', yob: 2001 },
      { uniform: '35', name: 'Koen Ghijsen',        pos: 'P',  bt: 'R/R', yob: 2008 },
      { uniform: '31', name: 'Terrance Heemskerk',  pos: 'IF', bt: 'L/R', yob: 2005 },
      { uniform: '27', name: 'Jim Hoyer',           pos: 'IF', bt: 'R/R', yob: 2007 },
      { uniform: '2',  name: 'Sheadion Louisa',     pos: 'IF', bt: 'R/R', yob: 2006 },
      { uniform: '30', name: 'Joel Martis',         pos: 'P',  bt: 'R/R', yob: 1998 },
      { uniform: '8',  name: 'Tyrell Mercado Reyes',pos: 'P',  bt: 'R/R', yob: 2007 },
      { uniform: '36', name: 'Sem Nijman',          pos: 'P',  bt: 'L/L', yob: 2004 },
      { uniform: '26', name: 'Jeldwin Orman',       pos: 'OF', bt: 'R/R', yob: 1991 },
      { uniform: '8',  name: 'Sebastian Perez',     pos: 'C',  bt: 'S/R', yob: 2006 },
      { uniform: '19', name: 'Quishawn Pieternella', pos: 'IF', bt: 'R/R', yob: 2002 },
      { uniform: '4',  name: 'Mees Robberse',       pos: 'C',  bt: 'R/R', yob: 2004 },
      { uniform: '11', name: 'Toss Spekking',       pos: 'IF', bt: 'R/R', yob: 2008 },
      { uniform: '16', name: 'Kaj Timmermans',      pos: 'P',  bt: 'R/R', yob: 1995 },
      { uniform: '23', name: 'Jayden Van Atten',    pos: 'IF', bt: 'R/R', yob: 2006 },
      { uniform: '44', name: 'Jesse Van Es',        pos: 'P',  bt: 'R/R', yob: 2002 },
      { uniform: '34', name: 'Sjors Art Van Gool',  pos: 'P',  bt: 'R/R', yob: 2010 },
      { uniform: '74', name: 'Kimi Verkruijssen',   pos: 'P',  bt: 'R/R', yob: 2007 },
      { uniform: '22', name: 'Koen Werkman',        pos: 'OF', bt: 'R/R', yob: 1992 },
      { uniform: '13', name: 'Miquel Willem',       pos: 'OF', bt: 'L/L', yob: 2005 },
    ],
    coaches: [
      { uniform: '38', name: 'René Baltus',    role: 'Manager/Head coach' },
      { uniform: '24', name: 'Roy Berrevoets', role: 'Coach' },
      { uniform: '17', name: 'Ronald Jaarsma', role: 'Coach' },
      { uniform: '33', name: 'Rene Rijst',     role: 'Pitching Coach' },
    ],
  },

  kinheim: {
    players: [
      { uniform: '34', name: 'Mart Blijleven',      pos: 'OF',  bt: 'L/L', yob: 2003 },
      { uniform: '40', name: 'Finn Blokker',        pos: 'P',   bt: 'R/R', yob: 2001 },
      { uniform: '19', name: 'Robyn Clara',         pos: 'P',   bt: 'R/R', yob: 1995 },
      { uniform: '8',  name: 'Max Draijer',         pos: 'IF',  bt: 'R/R', yob: 1997 },
      { uniform: '21', name: 'Aidan Finnegan',      pos: 'OF',  bt: 'R/R', yob: 2000 },
      { uniform: '29', name: 'Nick Hofer',          pos: 'OF',  bt: 'R/R', yob: 2001 },
      { uniform: '74', name: 'Nick Keur',           pos: 'P',   bt: 'L/L', yob: 1997 },
      { uniform: '32', name: 'Tristan Kuijer',      pos: 'IF',  bt: 'R/R', yob: 2007 },
      { uniform: '12', name: 'Donny Kuijper',       pos: 'IF',  bt: 'R/R', yob: 1999 },
      { uniform: '18', name: 'Thomas Maathuis',     pos: 'IF',  bt: 'R/R', yob: 2002 },
      { uniform: '89', name: 'Fregin Martina',      pos: 'P',   bt: 'R/R', yob: 2004 },
      { uniform: '6',  name: 'Jayden Mohamed',      pos: 'IF',  bt: 'R/R', yob: 2004 },
      { uniform: '55', name: 'Rick Rizvić',         pos: 'P',   bt: 'L/L', yob: 2003 },
      { uniform: '20', name: 'Tom Stuifbergen',     pos: 'P',   bt: 'R/R', yob: 1988 },
      { uniform: '30', name: 'Rick Timmermans',     pos: 'P',   bt: 'R/R', yob: 1999 },
      { uniform: '23', name: 'Guus Toemen',         pos: 'OF',  bt: 'R/R', yob: 2008 },
      { uniform: '27', name: 'Jair Van Borkulo',    pos: 'C',   bt: 'R/R', yob: 2002 },
      { uniform: '28', name: 'Sander Van Der Meer', pos: 'IF',  bt: 'R/R', yob: 2007 },
      { uniform: '5',  name: 'Luca Van Gorkum',     pos: 'OF',  bt: 'L/R', yob: 2002 },
      { uniform: '9',  name: 'Jayvon Vicario',      pos: 'C/IF',bt: 'R/R', yob: 2006 },
      { uniform: '41', name: 'Daniel Vos',          pos: 'P',   bt: 'R/R', yob: 2000 },
      { uniform: '31', name: 'Lorenzo Willem',      pos: 'C/IF',bt: 'R/R', yob: 2008 },
      { uniform: '13', name: 'Noah Zavolas',        pos: 'P',   bt: 'R/R', yob: 1996 },
    ],
    coaches: [
      { uniform: '4',  name: 'Milan Lammerts',              role: 'Manager/Head coach' },
      { uniform: '47', name: 'David Bergman',               role: 'Pitching Coach' },
      { uniform: '43', name: 'Michael Crouwel',             role: 'Coach' },
      { uniform: '25', name: 'Al Morales Gomez',            role: 'Pitching Coach' },
      { uniform: '59', name: "Dirk Gijsbertus Van 't Klooster", role: 'Coach' },
    ],
  },

  neptunus: {
    players: [
      { uniform: '4',  name: 'Arthur Bonevacia',    pos: 'IF', bt: 'S/R', yob: 1988 },
      { uniform: '28', name: 'Rosario Campisano',   pos: 'P',  bt: 'R/R', yob: 2008 },
      { uniform: '55', name: 'Dre Celestijn',       pos: 'OF', bt: 'R/R', yob: 1991 },
      { uniform: '80', name: 'Darryl Collins',      pos: 'OF', bt: 'L/R', yob: 2001 },
      { uniform: '37', name: 'Tom De Blok',         pos: 'P',  bt: 'R/R', yob: 1996 },
      { uniform: '36', name: 'Aaron De Groot',      pos: 'P',  bt: 'R/R', yob: 1999 },
      { uniform: '1',  name: 'Christian Diaz',      pos: 'OF', bt: 'L/L', yob: 1989 },
      { uniform: '13', name: 'Jan Evertse',         pos: 'P',  bt: 'R/R', yob: 1995 },
      { uniform: '43', name: 'Ryan Huntington',     pos: 'P',  bt: 'L/L', yob: 1996 },
      { uniform: '20', name: 'Sheadion Jamanika',   pos: 'IF', bt: 'R/R', yob: 1998 },
      { uniform: '47', name: 'Drew Janssen',        pos: 'IF', bt: 'R/R', yob: 1999 },
      { uniform: '33', name: 'Kevin Kelly',         pos: 'P',  bt: 'R/R', yob: 1990 },
      { uniform: '24', name: 'Dwayne Kemp',         pos: 'IF', bt: 'R/R', yob: 1988 },
      { uniform: '32', name: 'Urving Kemp',         pos: 'IF', bt: 'R/R', yob: 1993 },
      { uniform: '49', name: 'Sem Kuijper',         pos: 'C',  bt: 'R/R', yob: 2003 },
      { uniform: '6',  name: 'Yurdion Martie',      pos: 'C',  bt: 'R/R', yob: 1999 },
      { uniform: '39', name: 'Shairon Martis',      pos: 'P',  bt: 'R/R', yob: 1987 },
      { uniform: '45', name: 'Dean Moust',          pos: 'P',  bt: 'R/R', yob: 2009 },
      { uniform: '30', name: 'Koen Postelmans',     pos: 'P',  bt: 'R/R', yob: 2000 },
      { uniform: '27', name: 'Marnix Ruben',        pos: 'OF', bt: 'R/R', yob: 2001 },
      { uniform: '77', name: 'Den Seelbach',        pos: 'IF', bt: 'R/R', yob: 1999 },
      { uniform: '2',  name: 'Louie Sienders',      pos: 'C',  bt: 'R/R', yob: 1992 },
      { uniform: '17', name: 'Jovendrick Sprock',   pos: 'OF', bt: 'R/R', yob: 2004 },
      { uniform: '8',  name: 'Chris Stuart',        pos: 'P',  bt: 'L/L', yob: 2002 },
      { uniform: '88', name: 'Juancarlos Sulbarán', pos: 'P',  bt: 'R/R', yob: 1989 },
      { uniform: '15', name: 'Bob Van Der Meer',    pos: 'IF', bt: 'R/R', yob: 1996 },
      { uniform: '18', name: 'Stijn Van Der Meer',  pos: 'IF', bt: 'L/R', yob: 1993 },
      { uniform: '72', name: 'Jovaughn Viotty',     pos: 'IF', bt: 'R/R', yob: 2002 },
    ],
    coaches: [
      { uniform: '9',  name: 'Greg Muller',       role: 'Manager/Head coach' },
      { uniform: '21', name: 'Jan Collins',       role: 'Bench Coach' },
      { uniform: '38', name: 'Harvey Gumbs',      role: 'Coach' },
      { uniform: '35', name: 'Diegomar Markwell', role: 'Pitching Coach' },
    ],
  },

  pioniers: {
    players: [
      { uniform: '17', name: 'Eddie Aucoin',           pos: 'P',  bt: 'R/R', yob: 1975 },
      { uniform: '32', name: 'Duncan Beljaards',       pos: 'C',  bt: 'R/R', yob: 2004 },
      { uniform: '44', name: 'Colin Broers',           pos: 'OF', bt: 'L/L', yob: 2007 },
      { uniform: '4',  name: 'Miles Burleson',         pos: 'OF', bt: 'R/R', yob: 2006 },
      { uniform: '7',  name: 'Tijani Dunlop',          pos: 'OF', bt: 'L/R', yob: 1999 },
      { uniform: '54', name: 'Roangeraud Fraai',       pos: 'IF', bt: 'R/R', yob: 2002 },
      { uniform: '69', name: 'Aldrich Guzman',         pos: 'IF', bt: 'R/R', yob: 1993 },
      { uniform: '12', name: 'Cayro Hazel',            pos: 'IF', bt: 'R/R', yob: 2008 },
      { uniform: '0',  name: 'Peter Hegeman',          pos: 'P',  bt: 'L/L', yob: 2002 },
      { uniform: '2',  name: 'Raul Jacobs',            pos: 'IF', bt: 'R/R', yob: 1997 },
      { uniform: '52', name: 'Rik Jalvingh',           pos: 'P',  bt: 'R/L', yob: 1998 },
      { uniform: '10', name: 'Wesley Jansen',          pos: 'P',  bt: 'L/L', yob: 2001 },
      { uniform: '24', name: 'Andreas Meijer',         pos: 'IF', bt: 'R/R', yob: 2001 },
      { uniform: '29', name: 'Quendryson Reinilia',    pos: 'C',  bt: 'R/R', yob: 1999 },
      { uniform: '3',  name: 'Axcel Rodriguez',        pos: 'OF', bt: 'R/R', yob: 1998 },
      { uniform: '11', name: 'Timothy Rojas',          pos: 'IF', bt: 'S/R', yob: 2002 },
      { uniform: '0',  name: 'Rodin Smidt',            pos: 'P',  bt: 'R/R', yob: 2007 },
      { uniform: '27', name: 'Maarten Smit',           pos: 'P',  bt: 'L/L', yob: 2005 },
      { uniform: '89', name: 'Anjel Susana',           pos: 'P',  bt: 'L/L', yob: 2003 },
      { uniform: '18', name: 'Lucca Van Der Schouw',   pos: 'P',  bt: 'L/L', yob: 2000 },
      { uniform: '0',  name: 'Tygo Van Straten',       pos: 'P',  bt: 'R/R', yob: 2007 },
      { uniform: '9',  name: 'Kevin Wiegers',          pos: 'IF', bt: 'R/R', yob: 2001 },
      { uniform: '13', name: 'Eeuwe Winkel',           pos: 'P',  bt: 'R/R', yob: 2001 },
      { uniform: '25', name: 'Clay Winklaar',          pos: 'OF', bt: 'R/R', yob: 2006 },
    ],
    coaches: [
      { uniform: '36', name: 'Raymond Beljaards', role: 'Coach' },
      { uniform: '69', name: 'Aldrich Guzman',    role: 'Coach' },
      { uniform: '21', name: 'Tom Van Limburg',   role: 'Pitching Coach' },
    ],
  },

  twins: {
    players: [
      { uniform: '27', name: 'Nelmerson Angela',      pos: 'P',  bt: 'L/L', yob: 1998 },
      { uniform: '16', name: 'Railison Bentura',       pos: 'IF', bt: 'R/R', yob: 2000 },
      { uniform: '13', name: 'Luuk Bun',              pos: 'OF', bt: 'R/R', yob: 2002 },
      { uniform: '10', name: 'Lucas Den Duijn',        pos: 'P',  bt: 'R/R', yob: 2004 },
      { uniform: '7',  name: 'Dion Frank',            pos: 'C',  bt: 'R/R', yob: 2001 },
      { uniform: '26', name: 'Terrence Garcia',        pos: 'IF', bt: 'L/L', yob: 1994 },
      { uniform: '17', name: 'Simon Gross',           pos: 'P',  bt: 'R/R', yob: 2001 },
      { uniform: '19', name: 'Misja Harcksen',        pos: 'P',  bt: 'R/R', yob: 1995 },
      { uniform: '34', name: 'Zane Hendrickx',        pos: 'P',  bt: 'R/R', yob: 2004 },
      { uniform: '12', name: 'Ayumu Ishikawa',        pos: 'P',  bt: 'R/R', yob: 1988 },
      { uniform: '55', name: 'Finn Kops',             pos: 'P',  bt: 'R/R', yob: 2001 },
      { uniform: '14', name: 'Wyatt Paul Lankford',   pos: 'P',  bt: 'R/R', yob: 1998 },
      { uniform: '11', name: 'Dienston Manuela',      pos: 'P',  bt: 'L/L', yob: 1993 },
      { uniform: '9',  name: 'Nando Mostaert',        pos: 'IF', bt: 'R/R', yob: 2006 },
      { uniform: '6',  name: 'Rob Paller',            pos: 'OF', bt: 'L/R', yob: 1993 },
      { uniform: '2',  name: 'Thijmen Peters',        pos: 'IF', bt: 'R/R', yob: 2001 },
      { uniform: '28', name: 'Axel Poesmans',         pos: 'C',  bt: 'R/R', yob: 1996 },
      { uniform: '44', name: 'Yves Poesmans',         pos: 'OF', bt: 'R/R', yob: 1996 },
      { uniform: '30', name: 'Rens Romgens',          pos: 'P',  bt: 'R/R', yob: 2004 },
      { uniform: '5',  name: 'Faas Sluijter',         pos: 'IF', bt: 'L/R', yob: 2003 },
      { uniform: '89', name: 'Stijn Van Der Schaaf',  pos: 'P',  bt: 'R/R', yob: 2004 },
      { uniform: '18', name: 'Ben Van Dulken',        pos: 'C',  bt: 'R/R', yob: 2001 },
      { uniform: '23', name: 'Jerzy Van Gool',        pos: 'IF', bt: 'R/R', yob: 1998 },
      { uniform: '3',  name: 'Onne Van Gool',         pos: 'IF', bt: 'R/L', yob: 2001 },
      { uniform: '37', name: 'Mauro Van Mook',        pos: 'P',  bt: 'R/R', yob: 2002 },
      { uniform: '8',  name: 'Gijs Van Zalingen',     pos: 'IF', bt: 'R/R', yob: 2002 },
      { uniform: '22', name: 'Daan Verpaalen',        pos: 'IF', bt: 'R/R', yob: 2000 },
      { uniform: '21', name: 'Jurgen Zwitzer',        pos: 'P',  bt: 'R/R', yob: 2000 },
    ],
    coaches: [
      { uniform: '4',  name: 'Rob Ushy',         role: 'Manager/Head coach' },
      { uniform: '24', name: 'Jacinto De Gouveia',role: '1st Base Coach' },
      { uniform: '43', name: 'Sven Hendrickx',   role: '3rd Base Coach' },
    ],
  },

  uvv: {
    players: [
      { uniform: '31', name: 'Christopher Anasagasti', pos: 'C',  bt: 'R/R', yob: 2003 },
      { uniform: '10', name: 'Zico Atmopawiro',        pos: 'IF', bt: 'R/R', yob: 2007 },
      { uniform: '24', name: 'Lucas Bekker',           pos: 'IF', bt: 'R/R', yob: 1999 },
      { uniform: '8',  name: 'Stijn Bruins Slot',      pos: 'P',  bt: 'R/R', yob: 2000 },
      { uniform: '26', name: 'Jordy Burger',           pos: 'OF', bt: 'L/L', yob: 1995 },
      { uniform: '17', name: 'Raylano Clarke',         pos: 'C',  bt: 'R/R', yob: 2009 },
      { uniform: '5',  name: 'Ruben Dekker',           pos: 'P',  bt: 'R/R', yob: 2001 },
      { uniform: '14', name: 'Riley Gonesh',           pos: 'P',  bt: 'R/R', yob: 1998 },
      { uniform: '3',  name: 'Valentijn Guillot',      pos: 'P',  bt: 'R/R', yob: 2008 },
      { uniform: '23', name: 'Ingmar Hutzezon',        pos: 'P',  bt: 'R/R', yob: 2003 },
      { uniform: '7',  name: 'Edvin Irausquin',        pos: 'P',  bt: 'R/R', yob: 2002 },
      { uniform: '11', name: 'Aaron Isenia',           pos: 'P',  bt: 'L/L', yob: 2000 },
      { uniform: '66', name: 'Marvin Jakobus',         pos: 'IF', bt: 'R/R', yob: 2001 },
      { uniform: '50', name: 'Jenseley Keyzer',        pos: 'P',  bt: 'R/R', yob: 2000 },
      { uniform: '16', name: 'Reyer Lind',             pos: 'IF', bt: 'R/R', yob: 2007 },
      { uniform: '27', name: 'Tilsaimy Melfor',        pos: 'IF', bt: 'R/R', yob: 2001 },
      { uniform: '32', name: 'Jorrit Patist',          pos: 'C',  bt: 'R/R', yob: 2007 },
      { uniform: '25', name: 'Dayrell Pieternella',    pos: 'OF', bt: 'R/R', yob: 1998 },
      { uniform: '99', name: 'Ruendrick Piternella',   pos: 'C',  bt: 'R/R', yob: 2001 },
      { uniform: '44', name: 'Elijah Rustenburg',      pos: 'P',  bt: 'R/R', yob: 2006 },
      { uniform: '9',  name: 'Casper Urbanus',         pos: 'P',  bt: 'R/R', yob: 2003 },
      { uniform: '13', name: 'Jurjen Van Zijl',        pos: 'P',  bt: 'R/R', yob: 1984 },
      { uniform: '95', name: 'Amar Van Zwieten',       pos: 'OF', bt: 'R/R', yob: 2002 },
      { uniform: '22', name: 'Geoffrey Verhoef',       pos: 'OF', bt: 'R/R', yob: 1996 },
      { uniform: '15', name: 'Jack Wagner',            pos: 'P',  bt: 'R/R', yob: 2002 },
      { uniform: '29', name: 'Sean Wout',              pos: 'P',  bt: 'R/R', yob: 1992 },
    ],
    coaches: [
      { uniform: '47', name: 'Chad Abernathy',    role: 'Manager/Head coach' },
      { uniform: '37', name: 'Jiorgeny Casimiri', role: 'Pitching Coach' },
      { uniform: '53', name: 'Cliff Foster',      role: 'Pitching Coach' },
      { uniform: '66', name: 'Marvin Jakobus',    role: 'Coach' },
    ],
  },
}

export default ROSTERS
