"""Generate a browser adapter from the maintained Swift sources (original 0.6.1 reference is archived).
Only platform I/O and rendering primitives are replaced. Game rules and screen
bodies stay in Swift. Generated files are reproducible, never hand edited.
"""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]/'game-runtime'
src=root/'Native';out=root/'Generated';out.mkdir(exist_ok=True)
def write_generated(path,content):
    if not path.exists() or path.read_text()!=content:path.write_text(content)
def replace_function(s,name,body):
    m=re.search(r'(?m)^    (?:override )?func '+re.escape(name)+r'\b[^\n]*?\{',s)
    if not m:raise ValueError(name)
    start=m.start();pos=m.end();level=1
    # These platform helpers have no interpolated strings containing braces.
    while level:
        if s[pos]=='{':level+=1
        if s[pos]=='}':level-=1
        pos+=1
    return s[:start]+body+s[pos:]
for f in src.glob('*.swift'):
    if f.name in ['main.swift','Models.swift']:continue
    s=f.read_text().replace('import AppKit','import Foundation')
    if f.name=='Franchise.swift':s=s[:s.index('\nstruct FranchiseStore {')]
    if f.name=='FranchiseGuideView.swift':
        a=s.index('struct FranchiseInterfacePreferences:');b=s.index('struct FranchiseTourStep')
        s=s[:a]+s[b:]
    if f.name=='FranchiseView.swift':
        s=re.sub(r'final class ManagerButton:[^\n]*\n','',s)
        s=s.replace('final class FranchiseView:NSView {','final class FranchiseView {\n    var needsDisplay=true')
        s=s.replace('timer:Timer?,','')
        a=s.index('    override var isFlipped');b=s.index('    func tick()',a)
        s=s[:a]+'''    init(frame:NSRect,db:Database,saveDirectory:URL) {
        self.db=db;store=FranchiseStore(directory:saveDirectory);interfacePreferences=FranchiseInterfacePreferences.read(from:saveDirectory)
    }
'''+s[b:]
        s=s.replace(';NSAccessibility.post(element:self,notification:.valueChanged)','')
        a=s.index('    func leagueFont(');b=s.index('    func backdrop(',a)
        s=s[:a]+'''    func text(_ s:String,_ x:CGFloat,_ y:CGFloat,_ size:CGFloat=22,_ color:NSColor?=nil,_ font:String="AvenirNextCondensed-DemiBold",_ width:CGFloat=1450){
        let name=font=="Impact" ? "ExtraBoldIt":(font.contains("Bold") || font.contains("Heavy") ? "ExtraBold":(font.contains("Light") ? "ExtraLight":"Regular"))
        Canvas.commands.append(["text",s,x,y,size,(color ?? white).css,name,width,0,0])
    }
    func paragraph(_ s:String,_ x:CGFloat,_ y:CGFloat,_ w:CGFloat,_ h:CGFloat,_ size:CGFloat=20,_ color:NSColor?=nil){
        Canvas.commands.append(["text",s,x,y,size,(color ?? muted).css,"Regular",w,h,4])
    }
    func image(_ path:String,_ r:NSRect,alpha:CGFloat=1,cover:Bool=false){
        Canvas.commands.append(["image",path,r.minX,r.minY,r.width,r.height,alpha,cover,cover && path=="Assets/Photos/neptunus-10.jpg" ? 0.20:0.50])
    }
'''+s[b:]
        a=s.index('    override func updateTrackingAreas');b=s.index('    override func draw(',a)
        s=s[:a]+s[b:]
        s=s.replace('override func draw','func draw')
        s=s.replace('NSGraphicsContext.saveGraphicsState();let t=AffineTransform(scaleByX:bounds.width/1600,byY:bounds.height/900);(t as NSAffineTransform).concat();areas=[]','Canvas.commands=[];areas=[]')
        s=s.replace('        NSGraphicsContext.restoreGraphicsState()','')
        a=s.index('    func localPoint(')
        s=s[:a]+'''    func pointer(_ x:Double,_ y:Double,click:Bool){
        let p=NSPoint(x:x,y:y)
        if click {if positionMenu && !positionDropdownRect.contains(p){positionMenu=false;return};if let a=areas.first(where:{$0.rect.contains(p)}){act(a.action)}}
        else {hover=areas.firstIndex{$0.rect.contains(p)} ?? -1;if hover>=0{focus=hover}}
    }
    func key(_ code:Int,_ characters:String,shift:Bool=false){
        if code==53 && tourStep != nil{act("tour:skip");return}
        if code==53 && positionMenu{positionMenu=false;return}
        if characters==" " && autoSim{act("stop");return}
        if code==53{if !modal.isEmpty{act("close")}else if autoSim{act("stop")}else if page=="hub" || page=="draft"{act("exit")}else{page="careers";focus=0};return}
        if code==36 || characters==" "{if areas.indices.contains(focus){act(areas[focus].action)};return}
        if [123,124,125,126,48].contains(code){let previous=code==123 || code==126 || (code==48 && shift);focus=(focus+(previous ? -1:1)+max(1,areas.count))%max(1,areas.count);hover = -1}
    }
}
'''
    write_generated(out/f.name,'// GENERATED by scripts/generate-franchise.py; edit adapter or maintained source intentionally.\n'+s)
s=(src/'Models.swift').read_text();a=s.index('struct Team:');b=s.index('final class Database')
s='import Foundation\n'+s[a:b]
write_generated(out/'Models.swift',s)
print('Generated',len(list(out.glob('*.swift'))),'Swift files')
